/* Generated by wayland-scanner 1.25.0 */

#ifndef XDG_TOPLEVEL_TAG_V1_ENUM_PROTOCOL_H
#define XDG_TOPLEVEL_TAG_V1_ENUM_PROTOCOL_H

#ifdef  __cplusplus
extern "C" {
#endif

#ifdef  __cplusplus
}
#endif

#endif
